export default {
  light: {
    primary: '#F0F2F5',
    onPrimary: '#161513',
    secondary: '#ffffff',
    onSecondary: '#1C1C22',
    gradient: 'linear-gradient(90deg, #b16cea 25%, #ff5e69 50%, #ff8a56 75%, #ffa84b 100%);',
  },
  dark: {
    primary: '#161513',
    onPrimary: '#F0F2F5',
    secondary: '#1C1C22',
    onSecondary: '#ffffff',
    gradient: 'linear-gradient(90deg, #b16cea 25%, #ff5e69 50%, #ff8a56 75%, #ffa84b 100%);',
  },
  fonts: {
    headline1: {
      'font-family': '"Bai Jamjuree", sans-serif;',
      'font-size': '84px;',
      'font-style': 'normal;',
      'font-weight': '700;',
      'line-height': '100%;',
      'text-shadow': '0px 4px 4px rgba(0, 0, 0, 0.25);',
    },
    display1: {
      'font-family': '"Bai Jamjuree", sans-serif;',
      'font-size': '72px;',
      'font-style': 'normal;',
      'font-weight': '700;',
      'line-height': '125%;',
    },
    display2: {
      'font-family': '"Bai Jamjuree", sans-serif;',
      'font-size': '64px;',
      'font-style': 'normal;',
      'font-weight': '700;',
      'line-height': '125%;',
    },
    headline2: {
      'font-family': '"Bai Jamjuree", sans-serif;',
      'font-size': '56px;',
      'font-style': 'normal;',
      'font-weight': '700;',
      'line-height': '125%;',
    },
    headline3: {
      'font-family': '"Bai Jamjuree", sans-serif;',
      'font-size': '48px;',
      'font-style': 'normal;',
      'font-weight': '700;',
      'line-height': '125%;',
    },
    headline4: {
      'font-family': '"Bai Jamjuree", sans-serif;',
      'font-size': '32px;',
      'font-style': 'normal;',
      'font-weight': '700;',
      'line-height': '125%;',
    },
    headline5: {
      'font-family': '"Bai Jamjuree", sans-serif;',
      'font-size': '24px;',
      'font-style': 'normal;',
      'font-weight': '700;',
      'line-height': '125%;',
    },
    headline6: {
      'font-family': '"Bai Jamjuree", sans-serif;',
      'font-size': '18px;',
      'font-style': 'normal;',
      'font-weight': '700;',
      'line-height': '125%;',
    },
    paragraph1: {
      'font-family': '"Inter", sans-serif;',
      'font-size': '18px;',
      'font-style': 'normal;',
      'font-weight': '400;',
      'line-height': '125%;',
    },
    paragraph2: {
      'font-family': '"Inter", sans-serif;',
      'font-size': '16px;',
      'font-style': 'normal;',
      'font-weight': '400;',
      'line-height': '125%;',
    },
    paragraph3: {
      'font-family': '"Inter", sans-serif;',
      'font-size': '14px;',
      'font-style': 'normal;',
      'font-weight': '300;',
      'line-height': '125%;',
    },
    title: {
      'font-family': '"Inter", sans-serif;',
      'font-size': '18px;',
      'font-style': 'normal;',
      'font-weight': '600;',
      'line-height': '125%;',
    },
    menu: {
      'font-family': '"Inter", sans-serif;',
      'font-size': '18px;',
      'font-style': 'normal;',
      'font-weight': '600;',
      'line-height': '125%;',
    },
  },
};
